name: Export CI

env:
  GODOT_VERSION: 3.4.2
  EXPORT_NAME: SpaceEvader
  GODOT_CI: barichello/godot-ci:3.4.2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      image: ${{ env.GODOT_CI }}
    timeout-minutes: 10
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable

      - name: print-godot-version
        run: |
          echo Building using Godot $GODOT_VERSION

      - name: Web Build
        run: |
          mkdir -v -p build/web
          godot -v --export "HTML5" build/web/index.html

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: web
          path: build/web
  
#      - name: Deploy to GitHub Pages 🚀
#        uses: JamesIves/github-pages-deploy-action@releases/v4
#        with:
#          branch: gh-pages # The branch the action should deploy to.
#          folder: build/web # The folder the action should deploy.
    
